kubernetes-sigs/krew

pkg/index/indexscanner/scanner.go
pkg/index/indexscanner/scanner_test.go

Currently we may want to allow cahnges to
the index manifest format. The current approach
can break users that are on old versions.

Disable strict versioning

---

docs/DEVELOPER_GUIDE.md

This PR fixes typo of `shortDescription` field name.

Fix typo of shortDescription

---

docs/DEVELOPER_GUIDE.md

Golang's GOOS for macOS is "darwin", so this PR fixes to use "darwin" instead of "macos" for the value of platform selector.

Use "darwin" instead of "macos" for the value of platform selector

---

cmd/krew/cmd/search.go

This PR improves krew search not to output header when no plugins found.
/fix #13

krew search: doesn't output header when no plugins found

---

cmd/krew/cmd/version.go
hack/build-cross-releases.sh
pkg/version/version.go
pkg/version/version_test.go

I'm not entirely sure if we need both GitTag and GitCommit. This is primarily
for tagging release binaries easily (where the git repo is supposed to exist).
Fixes #20.

pkg/version: add git version stamps to krew binary

---

cmd/krew/cmd/info.go
pkg/index/indexscanner/scanner.go
pkg/index/indexscanner/scanner_test.go

This PR improves `krew info`'s error message when plugin does not exist.
```
$ kubectl plugin info hoge
Error: plugin "hoge" not found
Usage:
krew info [flags]
Flags:
-h, --help   help for info
Global Flags:
--alsologtostderr                  log to standard error as well as files
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory
--logtostderr                      log to standard error instead of files (default true)
--stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
-v, --v Level                          log level for V logs
--vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered …
```

krew info: Improve error message when plugin doesn't exist

---

docs/DEVELOPER_GUIDE.md
docs/NAMING_GUIDE.md

This is to be used/enforced in krew index and document best practices for the
plugin dev community.

docs: add plugin naming guide

---

cmd/krew/cmd/root.go
pkg/environment/environment.go
pkg/environment/environment_test.go
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/types.go
pkg/index/validate.go
pkg/index/validate_test.go
pkg/installation/move.go

This CL adds a bin field.
Bin specifies the entry point for a kubectl plugin after the 1.12 release.

Add BIN, entrypoint field for kubectl 1.12

---

.gitignore
.travis.yml
README.md
cmd/krew/cmd/root.go
pkg/environment/environment.go
pkg/environment/environment_test.go
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/types.go
pkg/index/validate.go
pkg/index/validate_test.go
pkg/installation/move.go

Looks like this:
$ out/build/krew-darwin update
W0912 12:58:28.998960    8579 root.go:43] Upcoming breaking change notice:
+++++++++++++++++++++++++++++++++++++++++++++++++
WARNING: krew will soon introduce breaking changes to move to
the new plugin system introduced in kubectl v1.12 and it will stop
working until it a newer version of krew is reinstalled.
This version of krew is compatible only with kubectl v1.11.
+++++++++++++++++++++++++++++++++++++++++++++++++
Updated index

add breaking change notice to all krew cmds

---

pkg/installation/move.go
pkg/installation/move_test.go

- detect empty globs
- may indicate typo
- may indicate changes in the archive structure but plugin manifest is out
of date
- fix test name
- use %#v for printing FileOperation in verbose logs

pkg/installation: prevent empty glob operations

---

pkg/installation/install.go
pkg/installation/install_test.go
pkg/installation/util.go

For dashes to be preserved in a plugin's name, its executable name must convert
dashes to underscores.
For example a plugin named "foo-bar" would today be linked as:
kubectl-foo-bar
therefore, it can only be invoked as:
kubectl foo bar
However, linking the same plugin as:
kubectl-foo_bar
allows plugin to be called as:
kubectl foo-bar
kubectl foo_bar
- convert OS detection pluginNameToBin() to explicit input for testability
- test pluginNameToBin().
Fixes #59.

Convert dashes in plugin names to underscores

---

cmd/krew/cmd/root.go
pkg/environment/environment.go
pkg/environment/environment_test.go

- Changing ResolveLink to Realpath as it sounds more like a readlink/realpath
operation (e.g. it works on directories and regular files).
- Add unit tests.
- Refusing to run on _relative_ symlinks (add error).
- Use filepath.Clean.

pkg/env: add tests for ResolveLink and rename

---

README.md
pkg/environment/environment.go
pkg/environment/environment_test.go

Introduces a KREW_ROOT environment variable to allow overriding
the krew base installation directory (defaults to $HOME/.krew).
Updated installation instructions to add default path to bashrc/zshrc.
Fixes #58.

pkg/env: allow base path override with KREW_ROOT

---

.travis.yml
hack/build-cross-releases.sh

- allow customization of built os/arch (I use this to build darwin only when
I am developing)
- change out/build to out/bin (I think we should use something more standard
like ./dist instead out ./out in the first place but that can happen later)
- use globs while adding binaries to release (out/bin/krew-*)
- make sure .sha256 file has the same suffix as krew.zip (was krew-zip.sha256)

Refactor hack/build-cross-releases.sh

---

cmd/krew/cmd/install.go
pkg/index/indexscanner/testdata/testindex/dontscan.yaml
pkg/index/indexscanner/testdata/testindex/plugins/badplugin.yaml
pkg/index/indexscanner/testdata/testindex/plugins/badplugin2.yaml
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/indexscanner/testdata/testindex/plugins/notyaml.txt
pkg/index/indexscanner/testdata/testindex/plugins/wrongname.yaml
pkg/index/validate.go
pkg/index/validate_test.go

We currently do not check apiVersion in plugin manifests and fail other
validation steps like "bin field is missing". This is confusing to users.
Adding an apiVersion check. Right now it's an exact match, but it should be ok.
When we can figure out how to parse k8s apiVersion format and compare them,
we can refactor this into isMinAPIversion().
This will require updates to many testdata files next time apiVersion is bumped.

pkg/index: add manifest apiVersion check

---

cmd/krew/cmd/info.go
cmd/krew/cmd/root.go

- Added a decorator function that uses glog.V() to print stack traces from
pkg/errors with %+v.
- Fixed a minor bug where specifying a non-existing plugin name to "upgrade"
cmd was resulting in "" to be added to error string.
Examples:
➜  kubectl krew upgrade foobar
Updated index
➜  kubectl krew upgrade foobar -v=1
I1008 14:45:39.200042   15234 git.go:62] Going to run git pull --ff-only -v
From https://github.com/GoogleContainerTools/krew-index
= [up to date]      master     -> origin/master
Already up to date.
Updated index
I1008 14:45:39.669936   15234 scanner.go:74] Reading plugin "foobar"
F1008 14:45:39.670188   15234 root.go:51] ERROR=open /Users/ahmetb/.krew/index/plugins/foobar.yaml: no such file or directory
failed to load the index file for plugin foobar …

cmd: print stack traces for errors when glog.V>=1

---

pkg/installation/util.go
pkg/installation/util_test.go

KREW_OS and KREW_ARCH can be used to override the values inferred from the
current runtime. This makes it possible to test installation of manifests
containing multiple platform specs.
Fixes #69.

pkg/install: allow OS/arch overrides with env

---

pkg/installation/install.go
pkg/installation/install_test.go

This will allow .exe symlinks to be constructed successfully when
KREW_OS=windows is set, but krew is running on a different GOOS.

pkg/install: isWindows respects KREW_OS

---

cmd/krew/cmd/list.go
cmd/krew/cmd/search.go
cmd/krew/cmd/version.go

- convert 2-column printing code to general-purpose table printer (printTable)
- deduplicate tabwriter calls from list/version/search into printTable
- do not discard errors from printTable in cmds (return from RunE)
- cmd/version: do not sort fields (looks more organized)

cmd: refactor table printing code

---

cmd/krew/cmd/install.go
docs/DEVELOPER_GUIDE.md
pkg/download/fetch.go
pkg/installation/install.go
pkg/installation/upgrade.go

- rename --source to --manifest in install command.
- introduce --archive flag to install command to override the installation from
the uri specified in the manifest file.
- remove getFileFromArg() method (not needed)
This patch allows specifying both plugin yamls and archives to install cmd:
krew install --manifest foo.yaml --archive foo.zip
It does not download a file, but it still checks integrity (so it can be used to
check the manifest without uploading the archive anywhere).
The method signatures got very long but I think that's partially because
we probably didn't design the methods in install.go well (the code smell here
is the repetitive args passed from one method to another all the way down).

Allow mocking of url downloads with local file (--archive)

---

hack/Dockerfile.build
hack/build-cross-releases.sh
hack/cloudbuild-release.yaml
hack/cloudbuild.yaml

- Dockerfile: build environment
- cloudbuild*.yaml: steps for building and pushing artifacts
Fixes #84.

hack: add google cloud build steps

---

cmd/krew/cmd/install.go
cmd/krew/cmd/list.go
cmd/krew/cmd/root.go

Fixes #81. There's a bunch of odd rules in the parsing of stdin vs args vs
--manifest. We might need to simplify it and be more strict.

cmd: deduplicate isTerminal detection

---

.travis.yml
hack/make-all.sh
hack/make-binaries.sh
hack/make-release-artifacts.sh

- disable travis github deploys on tags (fixes #89)
- split binary building (can also be used during development) and release
artifact building (krew.{yaml,zip{,sha256}}). we should probably convert
this to a makefile sometime.

Refactor release scripts

---

cmd/krew/cmd/install.go

This ensures that we don't clone the index repo when krew installs itself via
krew install --manifest krew.yaml --archive krew.zip

cmd/install: do not ensureIndex on --manifest

---

cmd/krew/cmd/install.go
docs/USER_GUIDE.md

- print caveats before "installed %s"
- downgrade "will install plugin" to glog.v(2)
- add "installing plugin" before starting install so each plugin looks like
"installing %s" and "installed %s" (looks better while downloading binaries).

cmd: refactor install output

---

cmd/krew/cmd/info.go
cmd/krew/cmd/install.go

Example:
Installing plugin: ca-cert
CAVEATS:
\
|  This plugin needs the following programs:
|  * base64
/
Installed plugin: ca-cert
Installing plugin: debug-shell
Installed plugin: debug-shell
Installing plugin: exec-all
CAVEATS:
\
|  Usage:
|    kubectl plugin exec-all <RESOURCE_TYPE> <RESOURCE_NAME> -- <COMMAND>
|  This plugin needs the following programs:
|  * jq
|  * xargs
|  * bash
/
Installed plugin: exec-all
Installing plugin: gke-credentials
CAVEATS:
\
|  This plugin needs the following programs:
|  * gcloud
/
Installed plugin: gke-credentials
Installing plugin: mtail
CAVEATS:
\
|  This plugin needs the following programs:
|  * jq
/
Installed plugin: mtail
Installing plugin: node-admin
Installed plugin: node-admin

cmd: pretty print caveats output

---

docs/DEVELOPER_GUIDE.md

Note: used markdown-toc vscode extension to create the toc. It doesn't let
users to --no-firsth1, so I had to promote each heading by one.

docs: revamp the DEVELOPER_GUIDE

---

cmd/krew/cmd/upgrade.go
pkg/installation/upgrade.go

Code cleanup: Pushes krew's version detection down the stack to run only when
it's needed.
Manually tested:
I1014 10:46:26.337111   74266 install.go:150] Created symlink at "/Users/ahmetb/.krew/bin/kubectl-krew"
I1014 10:46:26.337126   74266 upgrade.go:65] Starting old version cleanup
I1014 10:46:26.337135   74266 upgrade.go:77] Handling removal for older version of krew
I1014 10:46:26.337181   74266 upgrade.go:86] Detected running krew version=308989054b891cde0639d8405ea04a18c22e8461ed695b08163c52f1756b7d41
I1014 10:46:26.337275   74266 upgrade.go:107] Remove old krew installation under "/Users/ahmetb/.krew/store/krew/247929916e4a325dc0ec3e4898d2ca11e966c9a23780dafd54cc598f4bed4b8f"
Upgraded plugin: krew

upgrade: resolve krew version only on self-upgrade

---

hack/make-release-notes.sh

example:
```
Installation
------------
To install this release, refer to the instructions at https://github.com/GoogleContainerTools/krew/blob/v0.2.0-rc.1/README.md.
Release Assets
--------------
Artifacts for this release can be downloaded from the following links.
It is recommended to follow [installation instructions](https://github.com/GoogleContainerTools/krew/blob/v0.2.0-rc.1/README.md)
and not using these artifacts directly.
- https://storage.googleapis.com/krew/v0.2.0-rc.1/krew.tar.gz
- https://storage.googleapis.com/krew/v0.2.0-rc.1/krew.tar.gz.sha256
- https://storage.googleapis.com/krew/v0.2.0-rc.1/krew.zip
- https://storage.googleapis.com/krew/v0.2.0-rc.1/krew.zip.sha256
Thanks to our contributors for helping out with v0.2.0-rc.1:
- Ahmet Alp Balkan
- Luk Burchard
- Nicolas …
```

hack: add make-release-notes script

---

hack/cloudbuild-release.yaml
hack/cloudbuild.yaml

Due to lack of plumbing of GCB, v0.2.0 binary was not stamped correctly.

hack: plumb in TAG_NAME and SHORT_SHA

---

pkg/installation/install.go
pkg/installation/install_test.go

Improved error message on`remove krew` action.
Added appropriate unit-test.
Fixes https://github.com/GoogleContainerTools/krew/issues/129

Added condition to remove command, to prevent remove krew action

---

cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
pkg/index/validate.go

This tool takes a manifest file and runs certain validation steps. It's meant
to test plugin manifests added to [krew-index](https://github.com/GoogleContainerTools/krew-index) install correctly (so far it has
found one broken manifest).
Fixes #148.
Related to #149 but doesn't fix it.

cmd/validate-krew-manifest: initial implementation

---

docs/USER_GUIDE.md

Encountered some typos in the user guide, including a wrong command, which might be confusing otherwise.

Fix typos in user guide

---

cmd/krew/cmd/info.go
docs/DEVELOPER_GUIDE.md
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/types.go
pkg/index/validate.go
pkg/index/validate_test.go

This PR adds `spec.homepage` field to the plugin manifest.
/close #157 
---
The `spec.homepage` field of the plugin manifest defines the url of the
plugin project homepage. The field value should be a valid url.
In addition, if the `spec.homepage` field is defined in plugin manifest,
`kubectl krew info` command displays that field value as HOMEPAGE as follows:
$ kubectl krew info krew
NAME: krew
URI: https://storage.googleapis.com/krew/v0.2.1/krew.tar.gz
SHA256: dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a
VERSION: v0.2.1
HOMEPAGE: https://github.com/GoogleContainerTools/krew
...

Add `spec.homepage` field to the plugin manifest

---

CONTRIBUTING.md
OWNERS
OWNERS_ALIASES
SECURITY_CONTACTS
code-of-conduct.md

https://github.com/kubernetes/kubernetes-template-project
/cc @juanvallejo @nikhita

Add OWNERS, kubernetes project template files

---

.travis.yml
cmd/krew/cmd/info.go
cmd/krew/cmd/install.go
cmd/krew/cmd/list.go
cmd/krew/cmd/remove.go
cmd/krew/cmd/root.go
cmd/krew/cmd/search.go
cmd/krew/cmd/update.go
cmd/krew/cmd/upgrade.go
cmd/krew/cmd/version.go
cmd/krew/main.go
cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
docs/DEVELOPER_GUIDE.md
docs/NAMING_GUIDE.md
docs/RELEASING_KREW.md
hack/Dockerfile.build
hack/krew.yaml
hack/make-binaries.sh
hack/make-release-notes.sh
pkg/environment/environment.go
pkg/index/indexscanner/scanner.go
pkg/installation/install.go
pkg/installation/install_test.go
pkg/installation/move.go
pkg/installation/move_test.go
pkg/installation/upgrade.go
pkg/installation/util.go
pkg/installation/util_test.go

Switch all repo references from `GoogleContainerTools` -> `kubernetes-sigs`

---

.travis.yml
cmd/krew/cmd/info.go
cmd/krew/cmd/install.go
cmd/krew/cmd/list.go
cmd/krew/cmd/remove.go
cmd/krew/cmd/root.go
cmd/krew/cmd/search.go
cmd/krew/cmd/update.go
cmd/krew/cmd/upgrade.go
cmd/krew/cmd/version.go
cmd/krew/main.go
cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
hack/Dockerfile.build
hack/make-binaries.sh
pkg/environment/environment.go
pkg/index/indexscanner/scanner.go
pkg/installation/install.go
pkg/installation/install_test.go
pkg/installation/move.go
pkg/installation/move_test.go
pkg/installation/upgrade.go
pkg/installation/util.go
pkg/installation/util_test.go

Switch imports to sigs.k8s.io/krew

---

README.md

Adds a description section to install krew with fish.
This should close #179

add: description how to install krew on fish

---

README.md
cmd/krew/cmd/uninstall.go
docs/DEVELOPER_GUIDE.md
docs/USER_GUIDE.md
pkg/installation/install.go
pkg/installation/install_test.go

The inverse of `install` is `uninstall`, so this PR renames `krew remove`
to `krew uninstall`, and makes `krew remove` an alias to `krew uninstall`.
/close #188

Rename `krew remove` to `krew uninstall`

---

.travis.yml
cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
hack/check-code-patterns.sh
pkg/constants/constants.go
pkg/download/downloader_test.go
pkg/environment/environment_test.go
pkg/index/types.go
pkg/index/validate.go
pkg/index/validate_test.go
pkg/installation/install_test.go
pkg/installation/move_test.go
pkg/testutil/TempDir.go
pkg/testutil/tempdir.go

This PR now validates the file extension in the krew manifest validator.
Also, krew now expects `kind: Plugin`, which was not validated at all.
Last, it adds a test util to create and cleanup temporary directories. Some uses of vanilla `ioutil.TempDir` were updated with the new utility.
Fix #190

Validate manifest file extension and kind field

---

cmd/krew/cmd/update.go

krew update fails with:
fatal: repository 'https://sigs.k8s.io/krew-index.git/'
not found\n": exit status 128

Fix IndexUrl to point to right url

---

pkg/gitutil/git.go

Unfortunately, this is not testable at the moment, but this should be covered in #198.
Close #199

Ensure index updates do not fail if the local and remote history diverge

---

cmd/krew/cmd/info.go

cmd: info: Support only one argument

---

README.md

Added link for contribution doc

---

cmd/krew/cmd/list.go
docs/CONTRIBUTOR_GUIDE.md
hack/run-integration-tests.sh
test/krew_test.go

These are based on #203 and should be merged after that one. Reviewing before #203 is merged makes also no sense :-/
The tests currently cover the happy path of all subcommands excluding `krew upgrade`. Upgrade is a special case because it needs two versions of a valid plugin. That will be difficult to set up and may be better in a separate PR.

More integration tests

---

OWNERS_ALIASES

Adding corneliusweig to owners. He has been consistently helping both with
krew and krew-index repositories in terms of:
- developing plugins himself
- taking a stab at krew machinery with large scale code refactors
- adding integration test suite to the project
- adding more validation and test cases
- increasing developer documentation
Some of his notable work:
- https://github.com/kubernetes-sigs/krew/pull/195
- https://github.com/kubernetes-sigs/krew/pull/183
- https://github.com/kubernetes-sigs/krew/pull/191
- https://github.com/kubernetes-sigs/krew/pull/201
- https://github.com/kubernetes-sigs/krew/pull/202
- https://github.com/kubernetes-sigs/krew/pull/203
- https://github.com/kubernetes-sigs/krew/pull/208
He is familiar with the codebase enough to officially review and approve …

Make corneliusweig a maintainer

---

.golangci.yml
cmd/krew/cmd/list.go
cmd/krew/cmd/root.go
cmd/krew/cmd/search.go
cmd/krew/cmd/uninstall.go
cmd/krew/cmd/update.go
cmd/krew/cmd/version.go
cmd/krew/main.go
cmd/validate-krew-manifest/main_test.go
docs/CONTRIBUTOR_GUIDE.md
hack/run-lint.sh
hack/verify-gofmt.sh
pkg/download/downloader_test.go
pkg/environment/environment_test.go
pkg/index/indexscanner/scanner.go
pkg/index/indexscanner/scanner_test.go
pkg/index/validate.go
pkg/index/validate_test.go
pkg/installation/install.go
pkg/installation/util_test.go
test/krew/index.go
test/krew/krew.go

As pointed out by @ahmetb  here https://github.com/kubernetes-sigs/krew/pull/195#discussion_r296912755, imports are not sorted correctly. This PR applies standard sort order so that local imports are separated in their own import group. In addition, it also configures the linters to fail if imports are not sorted as expected.

Put local imports in a separate import group

---

cmd/krew/cmd/info.go
cmd/krew/cmd/search.go
cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
hack/verify-code-patterns.sh
pkg/constants/constants.go
pkg/index/indexscanner/scanner.go
pkg/index/platform.go
pkg/index/platform_test.go
pkg/installation/util.go
pkg/installation/util_test.go

This PR includes some small refactorings which originally were part of #195 . In particular:
* move the expected ending for manifests into a code constant
* check that this code constant is not used outside of `constants.go`
* move the logic to match a target platform out of `installation` and into the `index` package.

Small refactorings for better code structure

---

.travis.yml
hack/ensure-kubectl-installed.sh
hack/run-integration-tests.sh

- install appropriate kubectl (goos/goarch)
- save it to $GOPATH/bin since "export $PATH" won't work outside a particular
script
- lowercase naming for local variables
Fixes #210.

hack: move out install_kubectl_if_needed

---

cmd/krew/cmd/search.go
cmd/validate-krew-manifest/main.go
pkg/index/indexscanner/scanner.go
pkg/index/indexscanner/scanner_test.go
pkg/index/types.go
pkg/index/validate.go

- cleaned up some obsolete todos (ref: #213), some still relevant
- removed PluginIndex type, as it wasn't used for any reason

Cleanup some TODOs

---

README.md

The scripts fails and outputs an error `cd: The directory '(mktemp -d)' does not exist`. This error appears because `()` in strings aren't generally recognized as subshells in fish. To fix this I set a variable which we use to `cd` to. There seems to be no way to quote subshell commands in fish correctly.

Fix readme for wrong use of fish subshell in string

---

hack/ensure-kubectl-installed.sh
hack/run-integration-tests.sh
test/krew/krew.go
test/krew_test.go

I was hoping to write more integration tets, but along the way I noticed some
issues with how we run integration tests.
This PR addressses few things about the integration tests that bugged me.
- do not actually run the test plugin, it's out of our tool's scope
- run only integration tests from the script (previously ./...)
- DO NOT use the host-krew, require KREW_BINARY to be set (we almost never want to use host-krew)
Fixes #224
Fixes #225
Fixes #227

Various fixes to integration tests

---

hack/verify-code-patterns.sh

This fixes an issue where sometimes bash returns 1 instead of 123
in the exitcode of the pipe. This simplifies the find|xargs|grep with
just grep.
Fixes #217

hack: update verify-code-patterns.sh

---

README.md

This PR fixes a broken link on README.md. `./issues` actually links to https://github.com/kubernetes-sigs/krew/blob/master/issues, but it is non-existent page.

Fix a broken link on README.md

---

pkg/installation/install.go

Looks like we didn't address the code review comment at
https://github.com/kubernetes-sigs/krew/pull/195#discussion_r296915679.
Copying the conversation from there:
> This is better because:
>
> - actually installing a plugin (extract files, symlink binary) but then failing
>   to store the receipt is okay (at most you'd be leaking some files)
> - claiming the plugin is installed (i.e. receipt exists) while it's not
>   installed is not okay.
> - tens of things can go wrong in `install()`, much fewer things can go wrong
>  in `receipt.Store()`, so makes sense to do it last.
/kind cleanup

pkg/installation: reorder receipt save & install()

---

hack/run-in-docker.sh
hack/sandboxed.Dockerfile

- build krew binary outside container (do not duplicate build process)
- allows binary to be refreshed without rebuilding container
this way, we preserve container session/state
- also good for not leaking unused images to docker engine
that needs to be cleaned up regularly
- mount KUBECONFIG inside the container (not sure if it's actually useful)
I probably won't use it (since GKE clusters require gcloud to work, too)
- made the script a bit friendlier to follow as a user.

hack/run-in-docker: refactoring

---

docs/DEVELOPER_GUIDE.md

Fix typo in the developer docs for plugin manifest

---

cmd/krew/cmd/list.go
cmd/krew/cmd/search.go

So far, the last column was labelled with `STATUS` and had three options
(installed, available, unavailable). This was hard to read because
installed and available have the same length, and `unavailable` was not
specific.
Now, the column is labelled `INSTALLED` with values
yes/no/unavailable on \<PLATFORM\>
In addition, I increased the padding between columns to _two spaces_ which looks cleaner. WDYT?
---
Sample output:
```
NAME                            DESCRIPTION                                         INSTALLED
access-matrix                   Show an access matrix for server resources          no
bulk-action                     Do bulk actions on Kubernetes resources.            unavailable on linux
ca-cert                         Print the PEM CA certificate of the current clu... …
```

Make output of `krew search` easier to read

---

hack/verify-code-patterns.sh
integration_test/testutil_test.go

Use `t.Logf` instead of `glog` in tests

---

docs/CONTRIBUTOR_GUIDE.md
integration_test/testdata/konfig.yaml
integration_test/testutil_test.go
integration_test/upgrade_test.go

Only happy path so far.
Close #233

Add integration test for `krew upgrade`

---

.travis.yml
hack/verify-receipts-upgrade-migration.sh

This script makes sure as long as we have the 'system receipts-upgrade' command
upgrades from krew v0.2.1 to the currently built version works.
This should be deleted once the 'system receipts-upgrade' command is gone.
/hold
rebase + merge after #249 (tests expected to fail until then)

hack: add script to verify receipts migration

---

docs/CONTRIBUTOR_GUIDE.md
hack/make-binaries.sh
hack/make-binary.sh
hack/run-in-docker.sh

I've been finding myself doing a lot of:
OSARCH=darwin/amd64 hack/make-binaries.sh
this should help with that. I'm mostly making this change for myself.
/kind proposal

hack: add make-binary.sh for local builds

---

.travis.yml
hack/make-release-artifacts.sh
hack/verify-installation.sh

This script tests if a build is installable (as documented in the readme)
from its tarball+yaml file.
I felt like adding this as extra confidence on all the refactoring we're doing,
and I know we have integration tests that cover this. Since installation is
almost like our API, I thought it would be good to test.

hack: verify builds are installable

---

cmd/validate-krew-manifest/main_test.go
docs/DEVELOPER_GUIDE.md
docs/USER_GUIDE.md
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/validate.go
pkg/index/validate_test.go
pkg/info/info_test.go
pkg/receipt/receipt_test.go

No semver validation specifically just yet. Making the field required, and
planning to make it more strict later by actually parsing it.

Make version field required

---

cmd/krew/cmd/root.go
pkg/environment/environment.go
pkg/environment/environment_test.go
pkg/info/info.go
pkg/info/info_test.go
pkg/installation/install.go
pkg/installation/upgrade.go
pkg/receiptsmigration/migration.go

Purely method rename patch.
- InstallReceiptPath --> InstallReceiptsPath: indicating the path is containng
multiple receipts.
- PluginReceiptPath --> PluginInstallReceiptPath: making it clear to answer
"what receipt?" (A: install receipt), similarly consistent with the method
name above, just prefixed+singular.

minor: rename environment.Path receipt path methods

---

go.sum
hack/make-release-artifacts.sh
pkg/index/validate.go
pkg/index/validate_test.go
pkg/installation/semver/version.go
pkg/installation/semver/version_test.go

This package introduces a wrapper for `k8s.io/apimachinery/pkg/util/version`
package for its parts that we rely on for our handling of semver values.
go.{mod,sum} will likely conflict soon as there are other in-flight PRs.
Also refactored the validation code to verify 'version' value can be parsed.

semver: add wrapper for SemVer functionality

---

cmd/krew/cmd/list.go
cmd/krew/cmd/search.go
cmd/krew/cmd/upgrade.go
pkg/installation/util.go
pkg/receipt/receipt.go
pkg/receipt/receipt_test.go

- Changed the way we determine the list of "installed plugins" by looking at
install receipts directory.
- Added a receipt.Load() method for reading saved install receipts.

Update plugin listings to use install receipts

---

cmd/krew/cmd/install.go
pkg/download/verifier.go
pkg/installation/install.go
pkg/installation/upgrade.go
pkg/installation/util.go
pkg/installation/util_test.go

This change starts using semver version of plugin manifests to:
- determine if upgrade is needed
- determine if a plugin is installed
by looking at receipts installation directory. It doesn't help with other commands just yet.
This fixes #166, and helps with #277 partially.
Other commands are probably not yet using receipts entirely.

Refactor upgrade machinery to use semver versions

---

cmd/validate-krew-manifest/main_test.go
pkg/index/indexscanner/testdata/testindex/dontscan.yaml
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/validate.go
pkg/index/validate_test.go
pkg/info/info_test.go
pkg/installation/util_test.go
pkg/receipt/receipt_test.go

This makes sure the code only deals with valid lowercase sha256 values
(i.e. all lowercase) while doing comparisons etc.

pkg/index: validate sha256 values

---

cmd/krew/cmd/install.go
cmd/krew/cmd/upgrade.go

This option added to 'install' and 'upgrade' sub-commands allows users
(primarily developers) to test behavior locally (such as upgrades) while
preventing krew from auto-{updating,reverting,resetting} changes to the
local copy of the index repository at $KREW_ROOT/index.
Introducing this flag as "experimental", this way we can delete it if we don't
like it in the future. It's provided as an "escape hatch". An alternative I
can think of is a file like `$dir/.noupdate` existing in the index repo, but
I think this is cleaner.
Two issues that are in my mind currently wrt this change:
1. I can't recide between `--no-update-index` vs `--no-index-update`. In our
`gcloud` conventions we tend to use `--no-$VERB-$NOUN` so I'm going with
this.
2. Writing integration tests currently sound unnecessary …

Add --no-update-index option to bypass updates

---

.travis.yml
hack/run-integration-tests.sh
hack/run-tests.sh

-v is only useful if you want to see all the test cases that are being run.
I don't think this is useful locally or in the build system. I've been having
trouble scrolling a lot and trying to find the FAIL: line.
Any failed test will still print its t.Log or stdout/stderr printing along with
the test method name, so this should be fine.
/kind cleanup

test: remove -v from tests

---

pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/validation/validate.go
pkg/index/validation/validate_test.go

- unexport validatePlatform as it's not used outside pkg/validation.
- introduce validateSelector that validates selectors for:
- unsupported keys
- nil selector
- empty selector (both for matchLabels and matchExpressions)
as these situations are not supported, such as no plugin is valid for all
platforms supported by krew.
Fixes #282, fixes #287.

pkg/validation: add selector validation

---

pkg/installation/util.go
pkg/installation/util_test.go

Removing unused method.
Aside: It would be good to have a lint check that validates that unexposed
methods are not used (maybe even for external methods).
/kind cleanup

pkg/installation: unused pluginVersionFromPath

---

cmd/krew/cmd/install.go
cmd/krew/cmd/list.go
cmd/krew/cmd/system.go
hack/verify-receipts-upgrade-migration.sh
integration_test/help_test.go
integration_test/install_test.go
integration_test/list_test.go
integration_test/testutil_test.go
integration_test/uninstall_test.go
integration_test/update_test.go
integration_test/upgrade_test.go

Added more tests or expanded existing tests to:
- cover args/stdin handling edge cases for `install` cmd
- cover status code of re-runs of `install`, `update`, and `remove`
- cover status when index not initialized in `remove`, `upgrade` and `install`
- several other minor adjustments
Fixes #294
Fixes #295

integration_test: add more test cases

---

cmd/krew/cmd/install.go
pkg/installation/install.go
pkg/installation/install_test.go
pkg/installation/move.go
pkg/installation/upgrade.go
pkg/installation/util.go
pkg/installation/util_test.go

- `getDownloadTarget()`: removed, it didn't do anything interesting.
- `downloadAndMove()`:
- renamed to `downloadAndExtract()` which better reflects the functionality
- reduced methods from 7 to 4
- refactored the "move" operation out of this method (decouples "move"
from "download+extract") and we now call "move" from install().
- added unit tests (both for downloading a file, and --archive override)
- introduced `installOperation` which contains the minimal information to
perform installation operation.
- introduced `InstallOpts` type to scale out (in the future)
- `install()`:
- accepts fewer arguments (2) than before (8)
- no longer knows about index.Plugin, or environment.Paths
- cmd/install: removed a redundant check detecting specifying plugin names
along with --manifest option. …

pkg/installation: cleanup refactoring

---

docs/DEVELOPER_GUIDE.md
pkg/index/indexscanner/testdata/testindex/dontscan.yaml
pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
pkg/index/validation/validate.go
pkg/index/validation/validate_test.go
pkg/installation/install.go
pkg/installation/install_test.go
pkg/installation/move.go

Many plugins use the pattern to copy all files from the archive into the installation directory. Those plugins always have to specify a file copy operation such as
```yaml
files:
- from: "*"
to: "."
```
This PR makes the files field completely optional and defaults to the above copy specifier. As discussed in #135, the default copy spec may install too many files. The plugin developer docs therefore explicitly show such an antipattern example.
Close #135

Make files in `spec.platforms[]` optional

---

integration_test/uninstall_test.go

This validates the scenario that we can remove/rename plugins in the index
without breaking local user installations (since this is now possible with
the install receipts).

Validate plugins can be removed without local manifest

---

cmd/generate-plugin-overview/generate-plugin-overview.go

When resolving the index revision, be careful to always report a commit sha and not branch names.

Add index revision to plugin overview page

---

cmd/krew/cmd/upgrade.go

When loading plugin manifest fails, we create an error with
plugin.Name, but plugin instance is an empty struct, so .Name is
empty string.

prevent erroring with empty plugin name

---

pkg/download/downloader.go
pkg/installation/install.go

- Close file handle after extracting files on windows in extractTARGZ().
- Also ensure we close when io.Copy fails on extractZIP().
- Log the ignored error from the cleanup of DownloadPath.
Fixes #308.

pkg/download: close files after extracting in tar

---

docs/DEVELOPER_GUIDE.md

Adding a link to a GitHub template repo for Go projects creating krew plugins. This template has some of the best practices referenced in the guide implemented. The template also has GoReleaser configured to create a release on tag, a basic krew plugin.yaml, and all of the latest k8s client-go dependencies added and configured.
If there's a better place or wording for this, I'm happy to move/change it.

docs: Add link to GitHub template repo to developer guide

---

.errcheck-excluded.txt
.golangci.yml
cmd/krew/cmd/root.go
cmd/validate-krew-manifest/main.go
integration_test/testutil_test.go
pkg/download/downloader.go
pkg/download/verifier_test.go
pkg/receiptsmigration/migration_test.go

* add `.errcheck-excluded.txt` to disable some function calls as an example
* fixes #325

lint: enable errcheck and fix some issues

---

hack/run-lint.sh

bump golangci-lint to 1.18, various improvement and go 1.13
related #334

lint: bump golangci-lint to 1.18

---

README.md

This PR is a workaround for the failed push to master, see https://github.com/kubernetes-sigs/krew/issues/324#issuecomment-528763309

Update README.md for krew v0.3.0

---

.travis.yml
README.md
hack/krew.yaml
hack/make-release-artifacts.sh
hack/make-release-notes.sh

This patch removes krew.zip (previously used in krew.yaml as well as
windows installation instructions) and adds:
- krew.exe (to be used in first-time installation on windows)
- krew.exe.sha256 (checksum file)
ref: #338 
/hold

Remove krew.zip from release, add krew.exe

---

docs/RELEASING_KREW.md
hack/krew.yaml
hack/make-binaries.sh

- use tar.gz for installation smoke test on windows
- align manifest template with krew-index
- explicitly enable go modules when building the binaries

Minor fixes for the release

---

pkg/installation/install.go

`err` is nil here, so errors.Wrapf(...) is nil too, and that the calling code assumes that no error happened.
Fix #344

Fix handling when no matching platform is found

---

docs/RELEASING_KREW.md

This was necessary after permission changes due to the
repository migration to kubernetes-sigs.
/cc @ahmetb

Update release instructions

---

hack/run-lint.sh

Nothing serious, internal cleanup but some dep upgrades.

Upgrade golangci-lint to v1.19.1

---

docs/RELEASING_KREW.md

In the past this has caused other tags that aren't meant to be published to
be made public.

RELEASING_KREW: push only the release tag

---

pkg/pathutil/pathutil.go
pkg/pathutil/pathutil_test.go

* Add more test cases
* Fix misleading argument naming of `IsSubPath`
- subPath -> basePath
- path    -> subPath

Rely on standard utils for `IsSubPath`

---

docs/RELEASING_KREW.md

When pushing individual tags, specifying the repos is mandatory.
I also wasn't aware of this when reviewing #369 :face_with_head_bandage:
/assign @ahmetb

RELEASING_KREW: Specify the repository to push the tag to

---

hack/krew.yaml
hack/make-release-artifacts.sh

Ensure LICENSE is part of the release bundle for krew itself,
and is copied out to the resulting installation directory.

Distribute LICENSE

---

pkg/installation/install.go
pkg/installation/move.go
pkg/installation/move_test.go

It looks like we can generalize copyDir func as "copy" because filepath.Walk
works on regular files, too. Making single file move use this renameOrCopy
method.
Also fixed a typo.
This should fix #357.

Use renameOrCopy for single-file move operation

---

cmd/krew/cmd/install.go

This preserves the stack trace for errors from installation errors.
It impacts only when -v>0 specified (as that's when stack trace is printed).
Previously:
F1113 16:05:52.448852   29304 root.go:56] failed to install some plugins: [whoami]. error=install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:142
github.com/spf13/cobra.(*Command).execute
/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC …

Preserve installation error by wrapping

---

pkg/download/downloader_test.go
pkg/download/fetch.go

This fetcher was only used in its test.

Refactor: move errorFetcher struct to test file

---

pkg/download/downloader.go
pkg/download/fetch.go

This is a follow-up for #361 . I didn't realize that the logging was equally misleading.
Also see https://github.com/kubernetes-sigs/krew/pull/375#issuecomment-553653013

Make logging more consistent for downloaded vs. local archives

---

go.mod

Since we only develop via 1.13, it's a good idea to set min go to 1.13 to give a better error message if this is the issue.

Bump min go to v1.13 in go.mod

---

cmd/krew/cmd/search.go
pkg/index/validation/validate.go
pkg/index/validation/validate_test.go

Fail validation when manifest has line break in `shortDescription`

---

README.md

While checking #392, realized that krew version wasn't updated so this updates it.

Fix version in readme fish installation

---

hack/make-release-artifacts.sh

> warning: GZIP environment variable is deprecated; use an alias or script
handle warning with `-I / --use-compress-program=PROG`

Drop GZIP env in artifact building

---

cmd/krew/cmd/info.go
cmd/krew/cmd/install.go

Changes for https://github.com/kubernetes-sigs/krew/issues/402

Update post installation text

---

pkg/index/indexscanner/scanner.go

Turns out if there was a file in index/ directory with a non-.yaml extension,
we still targeted that as a plugin, so we tried to parse its manifest. (But
read/parsing of individual manifests do not cause fatal errors, just printed
to stderr like a warning.)
This creates a helper method that properly scans for .yaml files in an
immediate directory.
Fixes #412 

pkg/index: ignore non-.yaml files during scanning

---

hack/krew.yaml

Consistency with other plugin manifests at krew-index repository.

Remove license header from krew.yaml

---

hack/make-release-artifacts.sh

tar archive log was printed twice while exe archive wasn't printed.

[Release]: Fix log for exe archives

---

.travis.yml

Dro sudo config for travis.
Travis deprecated docker based environment and that's not used anymore.

Drop sudo from travis

---

README.md

For a fresh install, run krew update to initialize the local plugin index as part of the installation process to avoid the `plugin index is not initialized` error for first time user.

Update the installation instruction to also run krew update.

---

cmd/krew/cmd/install.go
cmd/krew/cmd/upgrade.go
hack/run-tests.sh

Fixes #431 
I decided to just use `os.IsNotExist` on the error rather than `errors.Is` since there's a package name conflict with the existing `github.com/pkg/errors` package. I was thinking about using the new %w verb in `fmt.Errorf` but noticed that you lose stack trace info when setting the log level. There's an existing issue, https://github.com/kubernetes-sigs/krew/issues/414, that is open to consider using 1.13 logging so I figured I'd use this for now and we could change it when the other issue gets figured out.

cmd: Friendly error messages when plugin not found

---

cmd/krew/cmd/root.go
cmd/validate-krew-manifest/main.go
hack/verify-code-patterns.sh

Came across during a code review, new contributors can end up using fmt.Errorf
which does not create stack trace at the error site --and also doesn't preserve
stack trace if used to wrap an error.

Disallow fmt.Errorf usage through code validation

---

docs/DEVELOPER_GUIDE.md

Mention that plugin source code needs to be public in order to be accepted for `krew-index`.
Also see https://github.com/kubernetes-sigs/krew-index/pull/386.

Add note to publish the plugin source code

---

.golangci.yml
cmd/generate-plugin-overview/generate-plugin-overview.go
cmd/validate-krew-manifest/main.go
cmd/validate-krew-manifest/main_test.go
go.sum
internal/download/downloader.go
internal/download/verifier.go
internal/installation/install.go
internal/installation/install_test.go
internal/installation/platform.go
internal/installation/platform_test.go
internal/installation/upgrade.go
internal/receiptsmigration/migration.go

Enable all rules from gocritic except some troublesome rules (see `.golangci.yml` for details).
Here is a part of what new rules bring:
* don't shadow imports or builtins such as
`os` and `close` respectively.
* use wrapper ReplaceAll
* combine types in func calls if same type
* find duplicate imports
* find suspicious regex
* ensure proper comment format
To fix some of the issues, I created a type for os and arch, then exported it.

Improve linting and fix found issues

---

cmd/krew/cmd/upgrade.go

Promoting this from log to user-visible message, because some plugins actually
are ~20-30 MiB and takes a significant time to download. During this time
we show no indication of progress while the download is happening.

Show "Upgrading plugin %s" message

---

integration_test/uninstall_test.go
internal/environment/environment.go
internal/environment/environment_test.go
internal/info/info_test.go
internal/installation/install_test.go
internal/receiptsmigration/migration_test.go
internal/receiptsmigration/oldenvironment/environment.go
internal/receiptsmigration/oldenvironment/environment_test.go

Expose `environment.NewPaths` to simplify test setup

---

cmd/krew/cmd/install.go
cmd/krew/cmd/install_test.go
cmd/krew/cmd/upgrade.go
cmd/validate-krew-manifest/main.go
integration_test/install_test.go
internal/index/indexscanner/scanner.go
internal/index/indexscanner/scanner_test.go
internal/info/info.go
internal/installation/receipt/receipt.go
internal/installation/receipt/receipt_test.go

Addressing some technical debt:
- Introduce indexscanner.ReadPlugin(io.ReadCloser)
- Make ReadPluginFromFile use that to simplify
- Move validation.ValidatePlugin from several places to ReadPlugin() method
- Add missing test for "preserves ENOENT" behavior for ReadPluginFromFile
- Fix verify-gofmt.sh reference (now gone) in run-tests.sh
Adding new stuff:
- introduce --manifest-url that is mut.ex. with --manifest and positional args
- add unit tests for url fetching
- add integration tests for --manifest-url argument behavior
Addresses #193, potentially supersedes #350.

Support reading manifest url from files

---

.golangci.yml

First disable all linters then enable what we need. Otherwise, all linters are running then results are filtered. See with `-v` flag.
Also, sort enabled linters in config.

Disable all first then enable needed linters

---

hack/run-lint.sh

Regular bump of lint tool to the latest.

Bump golangci-lint to v1.22.2

---

hack/run-lint.sh

Stable module supported pure go release.

Bump shfmt to v3

---

cmd/validate-krew-manifest/main.go

This came up in https://github.com/kubernetes-sigs/krew-index/pull/407.
We don't currently release krew for linux/arm64, but apparently linux/arm
distribution we have works there.
This would allow plugins to be distributed for linux/arm64, in addition to
existing linux/arm.

allow linux/arm64 plugins

---

.travis.yml

Sometimes when a dependency is added, it could be forgotten to be tidied.
This ensures it's always tidied.

Ensure go mod is tidied

---

docs/DEVELOPER_GUIDE.md

Let me know if the wording of this should be changed at all.
Fixes https://github.com/kubernetes-sigs/krew/issues/328

Add link to sample-cli-plugin in developer guide

---

hack/run-integration-tests.sh

- make this script accept KREW_BINARY for a custom binary path instead of $1
- pass args ($@) to "go test" so I can do stuff like "-v -run TestXyz"

run-integration-tests.sh: pass args down

---

integration_test/update_test.go

Tests when/how we show "New plugins available" and "Upgrades available for
installed plugins".
Adds ~3 seconds to integration tests.

integration tests for showing new/upgradeable plugins

---

cmd/krew/cmd/install.go
cmd/krew/cmd/internal/security_notice.go
cmd/krew/cmd/upgrade.go

The security notice was primarily meant for plugins installed from
krew-index, but this doesn't apply to krew as Krew is a sub-project
of SIG CLI and its source code has proper code reviews and audit trail.

don't print security notice for krew itself

---

cmd/krew/cmd/version.go
integration_test/testutil_test.go
integration_test/version_test.go

Add OS/Arch information in the krew version CLI output to help with diagnostics.
No unit test added since the function we are calling is already well tested.
Updated the KrewVersionTest integration test to convert the stdout to go map to leverage go-cmp for better test assertion. We now can report failure when new output is added to the `krew version` command.
Fixes #470

Add OS/Arch information in the krew version CLI output

---

.github/workflows/ci.yml

This fixes the old way to set GOPATH to PATH.
This way is used by Minikube too.
I tested it and it works perfectly. [logs](https://github.com/alonyb/krew/runs/421428433?check_suite_focus=true)

Set new GOPATH env var to github actions

---

cmd/krew/cmd/internal/setup_check.go
cmd/krew/cmd/internal/setup_check_test.go
cmd/krew/cmd/root.go

Fixes #485
Related https://github.com/Homebrew/homebrew-core/pull/49547
Homebrew refuses to add a post-install message for setting up
the PATH variable with krew's plugin store. Therefore we need
to check this on our side to warn users about an incomplete
setup. The goal is to
- print specific instructions for each shell/OS.
- not print the instructions when krew installs itself.

Check whether PATH has been set up correctly

---

.github/workflows/ci.yml

* whitespace (trim and indentation)
* step naming
* drop `id` from setup
Related to the comment: https://github.com/kubernetes-sigs/krew/pull/491#discussion_r374563885
Own initiative, feel free to close abruptly.

Improve github action

---

integration_test/version_test.go

Instead of full map comparison, relax it to be "map has all these keys with
the values that contain these strings".
This way, we can test krew version stamping (as it's not deterministic at
testing-time) as well as add more 'krew version' values without needing to
strictly match test.
Related issue: #496

make TestKrewVersion a substring check

---

hack/make-binaries.sh

fix version stamping in build script

---

internal/installation/util.go
internal/installation/util_test.go
internal/testutil/tempdir.go

Resolve todo and add unit test

---

internal/installation/upgrade.go

Install is much more likely to fail than storing the receipt.
Before, when the install failed, the new receipts was already
written to disk and not rolled back. Now, the receipt is only
stored when install has succeeded.
Fixes #502

Swap order of install and store receipt

---

cmd/krew/cmd/root.go
cmd/krew/cmd/system.go
internal/environment/environment.go
internal/indexmigration/migration.go
internal/indexmigration/migration_test.go

This only adds the migration code to change the directory structure that will be needed to support custom indexes. The other changes will be in subsequent PRs.
I'm using the existence of the ~~`index/default/`~~`index/.git` directory to indicate whether or not a migration needs to be performed.

Index migration

---

internal/pathutil/pathutil.go
internal/pathutil/pathutil_test.go
pkg/constants/constants.go

To be used in multi-index work.
cc: @chriskim06

add helper for inferring index name from input

---

internal/indexmigration/migration.go
internal/indexmigration/migration_test.go

This migrates the krew home to the new layout without an external dependency.
Related issue: #505
Also see https://github.com/kubernetes-sigs/krew/pull/505#discussion_r382856984
cc @chriskim06

Simpler migration without external dependency

---

cmd/krew/cmd/install.go
cmd/krew/cmd/root.go
cmd/krew/cmd/search.go
cmd/krew/cmd/system.go
cmd/krew/cmd/update.go
cmd/krew/cmd/upgrade.go
cmd/krew/cmd/version.go
integration_test/uninstall_test.go
integration_test/update_test.go
internal/environment/environment.go
internal/environment/environment_test.go
internal/indexmigration/migration.go
internal/info/info.go
internal/info/info_test.go
internal/receiptsmigration/migration.go
pkg/constants/constants.go

Add a name parameter to the index path functions (and behind the `X_KREW_ENABLE_MULTI_INDEX` variable) to return the path for the specified index, with "default" being implicit. Refactor the existing calls to use an empty string for now that gets ignored when the variable is unset.
The integration tests fail when `X_KREW_ENABLE_MULTI_INDEX` is set since the other functionality doesn't exist yet.

Refactor existing index path functions to support multiple indexes later on

---

site/config.yaml
site/content/_index.md
site/content/docs/_index.md
site/content/docs/developer-guide/_index.md
site/content/docs/developer-guide/release/submitting-to-krew.md
site/content/docs/user-guide/_index.md
site/content/docs/user-guide/quickstart.md
site/content/docs/user-guide/search.md
site/layouts/404.html
site/layouts/docs/section.html
site/layouts/docs/single.html
site/layouts/index.html
site/layouts/partials/backbutton.html
site/layouts/partials/footer.html
site/layouts/partials/header.html
site/layouts/partials/navbar.html
site/static/css/style.css
site/static/img/krew-logo.svg
site/static/krew-logo.svg

> Temporary staging at `http://staging.krew.dev/`
- added responsive collapsible navbar (+requires bootstrap.js, jquery)
- added a homepage (previously was docs ToC)
- added ToC pages for sub-sections (e.g. /docs/user-guide)
- add 404 page
- limit the content to 840px to avoid long lines on large screens
- move logo to /static/img
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
Related issue: #509 #514

site: Advanced website navigation

---

cmd/krew/cmd/internal/fetch_tag.go
cmd/krew/cmd/internal/fetch_tag_test.go

The krew CI has quite a few problems on travis, supposedly due to
API quota violation. For more meaningful errors, we now consider the
HTTP status code of the GitHub API response.
Fixes #516

Consider HTTP status for more meaningful errors

---

README.md
docs/RELEASING_KREW.md

This also simplifies the release process for krew, because the version
number does not need to be updated when releasing a new version.
Fixes #...

Use static URL to download assets from latest release

---

site/config.yaml
site/layouts/robots.txt

Prevent Netlify preview environments from being indexed by search bots.
If HUGO_ENV!=production, we return Disallow:/

site: robots.txt

---

netlify.toml
site/config.yaml
site/layouts/404.html
site/layouts/docs/section.html
site/layouts/docs/single.html
site/layouts/index.html
site/layouts/partials/footer.html

* pass page variables to footer
* use .GitInfo and .File variables to show something like this in the footer
for each page:
[Edit Page] - Built from commit [xxxx]
* enableGitInfo both locally and on Netlify builds

site: add gitinfo and edit links to footer

---

site/content/docs/developer-guide/develop/best-practices.md

Tell developers to have "kubectl " prefix ahead of their plugins' usage/help
messages.

docs: Add best practice on usage strings

---

site/content/docs/developer-guide/plugin-stats.md
site/layouts/docs/single.html

Add a page for plugin developers to browse stats for their dashboards.

docs: Document plugin stats dashboard

---

site/content/docs/developer-guide/develop/best-practices.md
site/content/docs/developer-guide/plugin-manifest.md
site/layouts/shortcodes/toc.html
site/static/css/style.css

Make it easier to grasp long docs pages by adding a Table of Contents snippet.
Example:
- https://deploy-preview-534--kubernetes-sigs-krew.netlify.com/docs/developer-guide/develop/best-practices/
- https://deploy-preview-534--kubernetes-sigs-krew.netlify.com/docs/developer-guide/plugin-manifest/

site: add toc snippet for long articles

---

site/layouts/partials/footer.html

Little JS snippet to actually show something like:
· Page last updated [3 days ago](link to commit).
Instead of:
· Build from commit [abcdef](link to commit).
Written in ES6 syntax (https://caniuse.com/#search=es6).

site: make footer show last updated

---

cmd/krew/cmd/index.go
internal/gitutil/git.go
internal/index/indexoperations/index.go
internal/index/indexoperations/index_test.go

Initial implementation of `kubectl krew index list`. This prints the indexes in a table in the same format as `kubectl krew list`:
```
$ KREW_ROOT="/home/kimc/playground" X_KREW_ENABLE_MULTI_INDEX=1 ./bin/krew-linux_amd64 index list
INDEX    URL
default  https://github.com/kubernetes-sigs/krew-index.git
```
I slightly refactored the `exec` function in gitutil to return the output of the command. The existing uses of it don't need it but I'm using the output from `git config --get remote.origin.url` to get the index's remote url. Let me know if there's a better way to get the url from git, that was the only way I knew how.

Add index list command

---

site/layouts/partials/footer.html
site/layouts/partials/header.html
site/layouts/partials/navbar.html
site/static/css/style.css

Instead of a shadowed box in the middle of the screen, sticking navbar to the
top and floating content in the middle. This is a bit more consistent with
current design patterns and more mobile-friendly.
If we like the preview, we can consider incorporating.

site: Alternative layout

---

internal/installation/util.go
internal/installation/util_test.go

Extract core of ListInstalledPlugins to filter installed plugin "by index"
(this will be used for `krew index delete`, to check if an index is being
deleted that has plugins installed).

add utility method to list installed plugins by index

---

cmd/krew/cmd/index.go
cmd/krew/cmd/root.go
integration_test/index_test.go
integration_test/testutil_test.go
internal/index/indexoperations/index.go
internal/index/indexoperations/index_test.go

Relatively small change. The majority of it is the test I added. I wasn't sure how to test the case where an index is added since it relies on git to clone the repo, so the only test cases I have are negative ones where the index with a name has already been configured and an invalid url is provided for the clone operation. I was thinking of using `constants.IndexURI` in a test case but didn't like that the unit test would need to be able to reach github so I didn't add it. 

Add index add command

---

.dockerignore
.github/workflows/ci.yml
.gitignore
README.md

After switching fully to GitHub Workflows we no longer use Codecov.io. We
also didn't really get much out of it.

remove codecov.io integration

---

cmd/krew/cmd/index.go
cmd/krew/cmd/internal/warning.go
cmd/krew/cmd/root.go
integration_test/index_test.go
internal/index/indexoperations/index.go
internal/index/indexoperations/index_test.go

Fixes #550
Related issue: #545, #483

cmd: Add 'index remove' command

---

cmd/krew/cmd/install.go
cmd/krew/cmd/upgrade.go
integration_test/install_test.go
internal/installation/install.go
internal/installation/receipt/receipt.go
internal/installation/receipt/receipt_test.go
internal/installation/upgrade.go

Populate receipt status on install/upgrade

---

cmd/krew/cmd/list.go
cmd/krew/cmd/search.go
cmd/krew/cmd/update.go
cmd/krew/cmd/upgrade.go
internal/installation/util.go
internal/installation/util_test.go

Small refactor that I think will be necessary for updating search/list/upgrade to work with custom indexes.

Refactor ListInstalledPlugins

---

site/content/docs/developer-guide/release/release-automation.md

Sadly `updating-plugins` was reused in two pages (this + `plugin-updates.md`).
I linked to this page from krew-index PRs several times.
But now we have to break that one in favor of this and have that link go to
the intended page in the first place.

site: fix slug for release-automation page

---

internal/installation/install.go

currently it appears that the pluginEntry type can just be in the
cmd/krew pkg. 
cc: @chriskim06

remove unused type installation.PluginEntry

---

cmd/krew/cmd/install.go
integration_test/install_test.go
integration_test/testutil_test.go

Let me know if you want me to move this out to a package level variable, figured it would be ok like this since this situation is only encountered in this file.

Use special "detached" index for manifest plugins

---

integration_test/install_test.go
integration_test/testutil_test.go

* refactor AssertPluginFromIndex
* no need to pass t
* mark as helper
* swap parameter order to match method name + more intuitive
* refactor existing "krew install" integ tests to use this
Related: #568

integration_test: Use new helper method

---

docs/CONTRIBUTOR_GUIDE.md

Fix a little mispelling in the docs regarding the `hack` folder

Fix mispelling of hack folder

---

docs/CONTRIBUTOR_GUIDE.md

Document that GNU binaries are required for the support scripts.
grep and sed are not part of the coreutils package so we need to install them as another package.

Document that gnu utils  are required in mac

---

hack/make-release-artifacts.sh

build untagged commits with + to indicate commit

---

integration_test/commandline_test.go
integration_test/index_test.go
integration_test/info_test.go
integration_test/install_test.go
integration_test/testutil_test.go
integration_test/uninstall_test.go
integration_test/update_test.go
integration_test/upgrade_test.go

- refactored ITest.Run() to return ([]byte,error)
- refactored all Run*** methods to use ITest.Run()
This also will help us test commands that are expected to fail but were
previously not making their stdout/stderr available to the test case for
string tests.
Fixes #561

integration_test: Refine cmd run utilities

---

cmd/krew/cmd/index.go
cmd/krew/cmd/install.go
cmd/krew/cmd/uninstall.go
cmd/krew/cmd/upgrade.go
integration_test/index_test.go
integration_test/install_test.go
integration_test/uninstall_test.go
integration_test/upgrade_test.go
internal/index/indexoperations/index.go
internal/index/indexoperations/index_test.go
internal/index/indexscanner/scanner.go

tl;dr: Some krew cmds are currently susceptible to path manipulation through positional arguments. Low-level machinery isn't responsible for this, so move them to cmd + add tests.
Moving plugin name or index name safety checks to cmd/ where they are given by
the user to the program. This way we shift the need for validation from being
unit tests of low-level machinery to the integration_test which tests
user-facing concerns.
> Note: Checks will fail until #582 is merged and this patch is rebased on it.
Fixes #581

Check index or plugin name safety in cmd

---

cmd/krew/cmd/search.go
integration_test/search_test.go

Mostly just refactoring. Added test to make sure search output is
alphabetically sorted (even in case of multiple indexes).
Related issue: #566, #483
/assign @chriskim06 
/assign @corneliusweig 

cmd: make krew search work with multiple indexes

---

cmd/krew/cmd/index.go
cmd/krew/cmd/update.go
cmd/krew/cmd/version.go
integration_test/index_test.go
integration_test/testutil_test.go
pkg/constants/constants.go

This change indicates the possibility of non-centralized plugin index. However,
this breaks the API (e.g. exported pkg/constants), so I'm not sure we should do
this.

constants: change the variable name

---

cmd/krew/cmd/search.go
integration_test/index_test.go

For some reason when we refactored the const name constants.IndexURI
https://github.com/kubernetes-sigs/krew/pull/584 its test run has inexplicably
succeeded https://github.com/kubernetes-sigs/krew/runs/559491631 despite some
references in main code + tests not updated.
(I appreciate if someone can take a look why that has happened.)
/priority P0

fix const references

---

site/content/docs/developer-guide/release/submitting-to-krew.md

site: fix some links, rewording

---

cmd/krew/cmd/update.go

* Adjusted the showUpdatedPlugins logic to behave well with multi-index mode
* Adjusted the "Updated the local copy of plugin index" message for multi-index
mode. (We won't show index name if it's 'default' index.)
Related issue: #566
/assign @corneliusweig 

Show new/updated plugins list after index updates

---

cmd/krew/cmd/install.go
cmd/krew/cmd/system.go
cmd/krew/cmd/update.go
cmd/krew/cmd/upgrade.go
integration_test/index_test.go

When user runs krew {install,update,upgrade} for the first time, if there are
no indexes, default index (with krew-index repo) is now automatically added.
Right now this code path only runs behind multi-index feature gate.
Related issue: #566

multi-index: Add default index if none exists

---

cmd/krew/cmd/namingutils.go
cmd/krew/cmd/namingutils_test.go
cmd/krew/cmd/uninstall.go
cmd/krew/cmd/upgrade.go
integration_test/uninstall_test.go
integration_test/upgrade_test.go

Upgrade was already refactored to support adding indexes to receipts so this was a pretty simple change + integration test. Upgrade works with:
- `kubectl krew upgrade`
- `kubectl krew upgrade plugin ... // plugin can be default/plugin or foo/plugin`
Also added warning text to uninstall when user tries to uninstall by canonical name.
Related issue: #566 

cmd: modify upgrade to work with multiple indexes

---

integration_test/index_test.go
integration_test/info_test.go
integration_test/install_test.go
integration_test/list_test.go
integration_test/search_test.go
integration_test/system_test.go
integration_test/testutil_test.go
integration_test/uninstall_test.go
integration_test/update_test.go
integration_test/upgrade_test.go

Two changes here:
- `WithIndex` -> `WithDefaultIndex`
- added `WithCustomIndex` function that does the cloning from the default index
I wasn't really sure if `WithCustomIndex` should call `initializeIndex` if it hasn't been initialized yet. It would clean up the code so that people don't have to call `WithDefaultIndex().WithCustomIndex("foo")` but I was worried that the cloning of krew-index was a little too hidden this way.
If I'm overthinking it let me know and I can change it up so that `WithCustomIndex` initializes krew-index if it hasn't been initialized yet.
Fixes #565
Related issue: #566

integration_test: Create helpers to initialize tests with custom indexes

---

cmd/generate-plugin-overview/generate-plugin-overview.go

Follow-up from @corneliusweig's [request in krew-index](https://github.com/kubernetes-sigs/krew-index/pull/623#issuecomment-636228575), I assume this change maps the name on [this page](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md) to the project website (vs the code repo).
Cheers,🍻

use kubetap homepage

---

cmd/generate-plugin-overview/generate-plugin-overview.go
hack/krew.yaml

So far, we have been redirecting to the github page. Our community page should be more useful in most cases however.

Redirect to Krew's new homepage in its manifest

---

cmd/validate-krew-manifest/main.go

Otherwise it is impossible to determine which manifest failed, if
multiple manifests are changed.

Include filename in manifest validator

---

.github/workflows/ci.yml
go.mod
hack/run-lint.sh

Also, bumps golangci-lint to v1.27.0 due to compatibility.
Fixes #606

Use go1.14 in github action

---

cmd/krew/cmd/index.go
cmd/krew/cmd/install.go
cmd/krew/cmd/upgrade.go
integration_test/index_test.go
integration_test/install_test.go
integration_test/upgrade_test.go

Right now I have the warning when the index is added as:
```
WARNING: You have added a new index from "/home/kimc/playground/temp"
The plugins in this index are not audited for security by the Krew maintainers.
Install them at your own risk.
```
let me know if you guys think I should change this.
Fixes #615 
Related issue: #576

Print security notice when index is added

---

cmd/krew/cmd/search.go
internal/index/indexscanner/scanner.go

In addition to adding the index name to the search error output as mentioned in https://github.com/kubernetes-sigs/krew/issues/614#issuecomment-647662430, I added some more info when a plugin (or receipt, figured might as well) fails to parse in the case of there being bad yaml in a custom index. This wasn't mentioned in the issue so if you guys feel we shouldn't include it I can remove it.
Fixes #614 
/cc @ahmetb 

Add more detail to error logging when dealing with bad index/plugin

---

.github/workflows/ci.yml
hack/verify-index-migration.sh

Adding automatic index migration ci test
Related issue: #566 
/cc @ahmetb 

Index migration ci test

---

cmd/krew/cmd/index.go
cmd/krew/cmd/info.go
cmd/krew/cmd/install.go
cmd/krew/cmd/root.go
cmd/krew/cmd/update.go
hack/verify-index-migration.sh
integration_test/index_test.go
integration_test/info_test.go
integration_test/install_test.go
integration_test/list_test.go
integration_test/migration_test.go
integration_test/search_test.go
integration_test/testutil_test.go
integration_test/uninstall_test.go
integration_test/update_test.go
integration_test/upgrade_test.go
internal/environment/environment.go
internal/environment/environment_test.go
internal/index/indexoperations/index.go
internal/index/indexoperations/index_test.go
pkg/constants/constants.go

Changes:
- remove the multi index flag
- update the `install` help message with an example for installing from a custom index
- update integration test function `WithDefaultIndex` to create an index in the migrated layout
Fixes #597 
Related issue: #566 
/cc @ahmetb 

Remove multi index flag

---

cmd/krew/cmd/upgrade.go
integration_test/upgrade_test.go

Skip upgrades for plugins installed via manifest

---

integration_test/index_test.go
integration_test/migration_test.go
integration_test/testutil_test.go
integration_test/upgrade_test.go

Use environment.Paths instead of calculating paths in integration tests

---

cmd/krew/cmd/internal/setup_check.go
cmd/krew/cmd/internal/setup_check_test.go

Previously this was rendering as
%!U(MISSING)SERPROFILE%!\(MISSING).krew\bin
while installing on windows. Using %% solves that.

fix path warning on windows

---

site/content/docs/developer-guide/plugin-manifest.md
site/content/docs/developer-guide/plugin-stats.md
site/content/docs/user-guide/setup/uninstall.md

In particular, consistently have bold heading in quote blocks.

Some fine-tuning of krew.sigs.k8s.io

---

cmd/krew/cmd/internal/setup_check_test.go
cmd/validate-krew-manifest/main_test.go
integration_test/commandline_test.go
integration_test/help_test.go
integration_test/index_test.go
integration_test/info_test.go
integration_test/install_test.go
integration_test/list_test.go
integration_test/migration_test.go
integration_test/search_test.go
integration_test/testutil_test.go
integration_test/uninstall_test.go
integration_test/update_test.go
integration_test/upgrade_test.go
integration_test/version_test.go
internal/download/downloader_test.go
internal/environment/environment_test.go
internal/index/indexoperations/index_test.go
internal/index/indexscanner/scanner_test.go
internal/indexmigration/migration_test.go
internal/installation/install_test.go
internal/installation/move_test.go
internal/installation/receipt/receipt_test.go
internal/installation/util_test.go
internal/receiptsmigration/migration_test.go
internal/testutil/tempdir.go

Go 1.14 comes with a `t.Cleanup()` method to register callbacks to be executed when the test is done (see https://golang.org/doc/go1.14#testing). This PR switches to this pattern.

Use go 1.14 `t.Cleanup()` for simpler tests

---

site/content/docs/user-guide/setup/install.md

Submitting the patch as discussed in https://github.com/kubernetes-sigs/krew/issues/630#issuecomment-674450714.
Fixes #630 
/cc @ahmetb 

Update installation instructions

---

cmd/validate-krew-manifest/main.go

Ensure platform spec extracts a (case-insensitive) {LICENSE,COPYING}{,.txt}
file by looking at the installation directory.
Fixes #641

validate-krew-manifest: add license check

---

cmd/krew/cmd/uninstall.go

Uninstall messages can look odd with custom indexes allowing
generic names:
Uninstalled plugin use
Uninstalled plugin build
So using a colon to separate it out like the "install" cmd.

tweak uninstall cmd message

---

site/layouts/partials/header.html
site/static/img/favicon.png
site/static/img/favicon.svg

Noticed there wasn't a favicon in the docs. Not sure if this is wanted, if not feel free to close
/area docs
/cc @ahmetb 

Add favicon

---

site/content/docs/user-guide/setup/install.md

Detect architecture with `uname -m` and use amd64 or arm to extract the binaries depending on the current system architecture.

Support arm architecture install

---

site/content/docs/user-guide/setup/install.md

Fixed use of fish shell evaluation with (...) instead of bash style $(…) in installation script in the specific fish section.
Tested and working well.

Fixed use of fish shell evaluation with (...) instead of bash style $(…)

---

cmd/krew/cmd/internal/setup_check.go
cmd/krew/cmd/internal/setup_check_test.go

Actually comparison between .krew/bin directory and path segment directory
is done with equal operator. This PR allow method filepath. Abs to be call during krew path creation
`/internal/environment/environment.go#L43` and also in `/cmd/krew/cmd/internal/setup_check.go#L62` path directory iteration
Fixes #664

Fix : sanitize PATH dir

---

cmd/krew/cmd/update.go
cmd/krew/cmd/version.go
pkg/index/util.go
pkg/index/util_test.go

Adding this based on the comment here https://github.com/kubernetes-sigs/krew/pull/666#discussion_r528472892. This reverts back `constants.go` so that it only has the constant values and adds a `pkg/index/util.go` that has the `DefaultIndex` function in it.
/assign @ahmetb 
/assign @corneliusweig 
Related issue: #637

Default index function

---

.golangci.yml
cmd/krew/cmd/install_test.go
cmd/krew/cmd/internal/setup_check_test.go
hack/run-lint.sh

See list of currently active linters by running
```
golangci-lint linters
```
/assign @chriskim06 
Fixes #639

Update golanci-lint to v1.33.0 and enable govet

---

OWNERS_ALIASES

Based on the steps outlined here https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process I think I need to be added to the OWNERS_ALIASES file
> Only people listed in the relevant OWNERS files, either directly or through an alias, as described above, can act as approvers, including the individual who opened the PR.

Add myself to owners alias

---

hack/krew.yaml
hack/make-binaries.sh
site/content/docs/user-guide/setup/install.md

Support linux/arm64 release

---

site/content/docs/developer-guide/custom-indexes.md
site/content/docs/developer-guide/develop/best-practices.md
site/content/docs/developer-guide/develop/naming-guide.md
site/content/docs/developer-guide/develop/plugin-development.md
site/content/docs/developer-guide/distributing-with-krew.md
site/content/docs/developer-guide/example-plugin-manifests.md
site/content/docs/developer-guide/installing-locally.md
site/content/docs/developer-guide/plugin-manifest.md
site/content/docs/developer-guide/plugin-stats.md
site/content/docs/developer-guide/release/plugin-updates.md
site/content/docs/developer-guide/release/release-automation.md
site/content/docs/developer-guide/release/submitting-to-krew.md

Here's most of the changes for the developer guide. I had a few questions on the doc but I figured I'd submit this portion for now (this is the large majority of the changes anyways).

Docs update - developer guide

---

cmd/validate-krew-manifest/main.go

Some plugins like https://github.com/jetstack/cert-manager store the license information in a file called LICENSES. This adds support for this filename to the manifest validation.
Fixes #691

Support LICENSES filename in manifest validation

---

integration_test/install_test.go
integration_test/testutil_test.go
integration_test/upgrade_test.go
internal/installation/install.go
internal/installation/receipt/receipt.go
internal/installation/receipt/receipt_test.go
internal/installation/upgrade.go

This PR adds the current time as the timestamp when a plugin is installed and leaves it alone when something is upgraded. I wasn't sure if we should do something about existing receipts with null `creationTimestamp`'s but figured it would be ok without something.
/assign @ahmetb 
/assign @corneliusweig 
Fixes #632

Add creation timestamp to receipts on install

---

hack/.gitignore
hack/install-gox.sh
hack/make-release-notes.sh
hack/run-lint.sh

cleaning up our hack/ scripts a bit.

hack: use go1.16 'go install pkg@ver' mode

---

.golangci.yml
hack/run-lint.sh

Since golangci-lint brought that functionality, use it instead of another dependency.

hack: drop impi in favor of golangci-lint

---

site/content/docs/developer-guide/custom-indexes.md
site/content/docs/developer-guide/develop/best-practices.md
site/content/docs/developer-guide/develop/naming-guide.md
site/content/docs/developer-guide/develop/plugin-development.md
site/content/docs/developer-guide/installing-locally.md
site/content/docs/developer-guide/plugin-manifest.md
site/content/docs/developer-guide/plugin-stats.md
site/content/docs/developer-guide/release/plugin-updates.md
site/content/docs/developer-guide/release/release-automation.md
site/content/docs/user-guide/using-custom-indexes.md

Here are the rest of the changes. There were a couple things I missed in my previous PRs and a couple changes based on the review in https://github.com/kubernetes-sigs/krew/pull/690

Docs follow up

---

internal/index/indexoperations/index.go

Fixes #...https://github.com/kubernetes-sigs/krew/issues/683
Related issue: #... ListIndexes treating file as index candidates

Fixed ListIndexes treating file as index candidates

---

internal/testutil/tempdir.go

**PR Summary:**
- Fixes #696
**For the reviewers:** 
I'm not sure this is the right implementation, as @ahmetb asked to _deprecate_ the implementation of `testutil.NewTempDir(t)` should I add some `deprecation notice`? Thanks in advance for the advices/reviews.

ISSUE-696: Explore use of t.TempDir()

---

site/content/docs/developer-guide/plugin-manifest.md

This is a follow-up to https://github.com/kubernetes-sigs/krew-index/pull/1157. Apparently, it was not sufficiently clear that the plugin name determines how a plugin is invoked.
Related issue: https://github.com/kubernetes-sigs/krew-index/pull/1157

Clarify the role of the plugin name

---

.github/workflows/ci.yml
docs/RELEASING_KREW.md
hack/krew.yaml
hack/make-release-artifacts.sh
hack/verify-installation.sh

Fixes #697 
In install instructions, use `--archive` (and therefore `--manifest-url`) to not download again the tarball when launching `krew install` command.

Release separated archives for each platform (#697)

---

cmd/krew/cmd/search.go

Searching images with krew on linux/arm64:
~~~plaintext
$ kubectl krew search images
NAME    DESCRIPTION                                 INSTALLED
images  Show container images used in the cluster.  unavailable on Linux
~~~
In fact, it just lacks support for linux/arm64.

Clearly state the operating system and architecture in the search result

---

cmd/validate-krew-manifest/main.go

I'm working in [integrating the generation of krew manifests into GoReleaser](https://github.com/goreleaser/goreleaser/pull/2639), and one thing I would like to do there is a test to validate that test-generated manifests are valid... 
But, while testing, the URLs are all faked, so, installing them won't work.
I would still like to be able to validate everything else though, so I added a new flag which we can pass `-install=false` so it won't actually install anything...
Happy to hear your thoughts on this!
Cheers!

feat: skip install on validate-krew-manifest

---

cmd/validate-krew-manifest/main.go

This PR updates validate-krew-manifest  to add windows/arm64 to supported platforms, because Go 1.17 added support of 64-bit ARM architecture on Windows.
- https://go.dev/doc/go1.17#windows

validate-krew-manifest: Add windows/arm64 to supported platforms

---

.github/workflows/ci.yml
go.mod

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
Fixes #...

Bump Go to 1.17

---

cmd/krew/cmd/root.go
integration_test/index_test.go

Fixes #750.
We shouldn't just check the default index.

check all existing index

---

site/content/docs/developer-guide/develop/naming-guide.md

I'm adding this based on convention I've seen with other plugins but if there's something else we recommend I'm fine with that too. This clarity can help plugin developers and companies looking for naming guidance and who want to avoid any trademark confusion.
Fixes #...

Adding clarity for plugin repo naming

---

cmd/krew/cmd/root.go

Related issue: #769
/assign @ahmetb 
```
$ ./out/bin/krew-darwin_amd64
krew is the kubectl plugin manager.
You can invoke krew through kubectl: "kubectl krew [command]..."
Usage:
kubectl krew [command]
Available Commands:
help        Help about any command
index       Manage custom plugin indexes
info        Show information about an available plugin
install     Install kubectl plugins
list        List installed kubectl plugins
search      Discover kubectl plugins
uninstall   Uninstall plugins
update      Update the local copy of the plugin index
upgrade     Upgrade installed plugins to newer versions
version     Show krew version and diagnostics
Flags:
-h, --help      help for krew
-v, --v Level   number for the log level verbosity
Use "kubectl krew [command] --help" for more information …
```

disable the completion command

---

cmd/krew/cmd/internal/setup_check.go

Related issue: #767
The instruction on https://github.com/kubernetes-sigs/krew/blob/93827db2b9954e356456f24cc030419a899e95b1/hack/krew.yaml#L13-L16 mentions `KREW_ROOT` but one on cmd/krew/cmd/internal/setup_check.go doesn't.
This tweaks that instruction to mention `KREW_ROOT` there too.
The fish command is a bit long as there's no simple alternative to the unset variables on fish AFAIK.

Mention `KREW_ROOT` on instruction

---

docs/KREW_LOGO.md

White links are not accessible.

Fix image links of logo

---

hack/run-lint.sh

Installation via https://install.goreleaser.com has been [deprecated](https://github.com/goreleaser/godownloader/issues/207) and now the server is unavailable, this replaces it with a recommend way stated on https://golangci-lint.run/usage/install/.
This will fix the CI issue e.g. https://github.com/kubernetes-sigs/krew/actions/runs/2384314784

Update the installation URL of golangci-lint

---

.github/workflows/ci.yml

The example release is here: https://github.com/2k36/krew/releases/tag/v0.100.2-rc.2
~~Note that the release body isn't rendered as Markdown since the latest release, opened #780 to track it.~~ Fixed!
This just replaces action with a new one, so nothing functional should have changed.
Fixes #776
Fixes #780

Replace an unmaintained action

---

README.md

To make it consistent with the number on website homepage: https://krew.sigs.k8s.io/

Update the number of kubectl plugins

---

cmd/validate-krew-manifest/main.go
docs/RELEASING_KREW.md
hack/krew.yaml
hack/make-binaries.sh
site/content/docs/developer-guide/plugin-manifest.md

Fixes #...
Added support for ppc64le architecture and therefore not really a feature content-wise

Add ppc64le support

---

hack/krew.yaml
site/content/docs/developer-guide/plugin-manifest.md

To make the plugin manifest doc better to new developers.

Update plugin manifest doc

---

site/content/docs/developer-guide/plugin-manifest.md

There has been an issue open for some time discussing Windows entrypoint support. The proposal since early 2022 is that we just document that only `.exe` entrypoints on Windows are supported as anything else is an edge case. There has been no objection since, so lets update docs and close the issue.
Fixes #131
/kind cleanup
/area docs

Document windows entrypoint limitation of .exe

---

hack/ensure-kubectl-installed.sh
hack/sandboxed.Dockerfile

The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
Related PRs:
- https://github.com/kubernetes-sigs/image-builder/pull/656
- https://github.com/kubernetes-sigs/cluster-api/pull/4958

Use dl.k8s.io instead of hardcoded GCS URIs

---

internal/download/fetch.go
internal/download/fetch_test.go

detect download failures when status code is > 200
#819

detect download failures when status code > 200

---

.github/workflows/ci.yml
docs/RELEASING_KREW.md
hack/make-release-notes.sh

fix contributors list in release notes

---

internal/installation/move.go

Because we're doing `mktemp` (which gives 0700) and then moving it to `$KREW_ROOT/store/PLUGIN/VERSION`, we need to make sure that the directory is 0755 like the other dirs in `store`.
See #840.

fix: chmod 0755 store/PLUGIN/VER dir

---

cmd/krew/cmd/index.go
cmd/krew/cmd/list.go
cmd/krew/cmd/uninstall.go

these are some aliases that homebrew has that i thought would be nice to include here as well (not that krew needs to mimic homebrew in every way, but still a minor convenience i think). the `ls` one isnt really a big deal but i think having `rm` as an option instead of `uninstall` or `remove` is nice. if theres a reason we dont want to include these though then its not a big deal. ive never heard of any complaints about this so its purely a "nice to have" in my mind.
/assign @ahmetb

add aliases to a few commands

---

cmd/krew/cmd/search.go
cmd/krew/cmd/search_test.go

Fixes https://github.com/kubernetes-sigs/krew/issues/862
I'm not really sure what might could be added to the tests to account for this.

Fixing search results

---

integration_test/search_test.go
integration_test/testutil_test.go

Related issue: #862 
/assign @ahmetb

use an exact number for search integration test

---

.github/workflows/ci.yml

Bumps utilized GitHub actions to latest stable releases (`setup-go`,`checkout` and `action-gh-release`)

Bump GitHub actions to latest stable
