- cmd/krew/cmd/search.go
- pkg/index/indexscanner/testdata/testindex/dontscan.yaml
- pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
- pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
- pkg/index/types.go
- pkg/index/validate.go
- pkg/index/validate_test.go
Change the "Intro" field to the more descriptive
"shortDescription" field.
> Change Intro plugin index field

- docs/DEVELOPER_GUIDE.md
This PR fixes invalid yaml in docs/DEVELOPER_GUIDE.md.
> Fix invalid yaml in DEVELOPER_GUIDE.md

- cmd/krew/cmd/install.go
- cmd/krew/cmd/upgrade.go
- pkg/index/indexscanner/scanner.go
- pkg/index/types.go
- pkg/index/validate.go
- pkg/installation/install.go
- pkg/installation/upgrade.go
- pkg/installation/util.go
- pkg/installation/util_test.go
This fixes lint errors mainly with inserting TODOS.
> Fix lint errors

- README.md
> Add Roadmap

- cmd/krew/cmd/root.go
> cmd: don't print usage and duplicate error msg

- pkg/download/downloader.go
- pkg/download/verifier.go
- pkg/download/verifier_test.go
> pkg/download: code cleanup for exports

- pkg/installation/install.go
returns friendlier error messaage for files not found in bin
> pkg/install: better error for not found bin files

- pkg/installation/move.go
- pkg/installation/move_test.go
> pkg/install: delete target dir upon directory move

- pkg/installation/install.go
- pkg/installation/install_test.go
- removeLink is now separated from plugin logic. moved plugin related argument
prep to call-site.
- removeLink now fails explicitly for non-symlinks. since bin/ is supposed to
be only symlinks, this sounds appropriate
- added test cases
- handled an ignored removeLink error in `installation.Remove()` method (this is supposed to be ok since we use the same symlink to resolve the plugin installation, so plugin is probably there...)
> removeLink: refactor and add tests

- .travis.yml
- hack/build-cross-releases.sh
Add the `arm` architecture to Gox to provide a new binary.
Binaries are named `krew-os_arch`.
Ex:
```
$ unzip -l out/krew.zip
Archive:  out/krew.zip
Length      Date    Time    Name             
---------  ---------- -----   ----                           
0  2018-09-24 11:14   out/build/                                                                  
0  2018-09-24 11:14   out/build/windows/                                                          
0  2018-09-24 11:14   out/build/windows/commands/
0  2018-09-24 11:14   out/build/windows/commands/install/
377  2018-09-24 11:14   out/build/windows/commands/install/plugin.yaml
0  2018-09-24 11:14   out/build/windows/commands/update/
261  2018-09-24 11:14   out/build/windows/commands/update/plugin.yaml
0  2018-09-24 11:14 …
```
> Support form ARM binary

- pkg/installation/util.go
> Skip non-directories in store dir while listing

- hack/build-cross-releases.sh
- set CGO_ENABLED=0
- use -w ldflags (no DWARF, ~20 smaller binaries)
- use -tags=netgo (pure Go net)
Fixes #85
Fixes #86
> hack: disable cgo and glibc dependencies

- .travis.yml
- hack/build-cross-releases.sh
- hack/krew.yaml
Update build script to ship the versioned yaml. This ships krew.yaml as part
of release. After release is complete, we just need to copy this file into
index repo.
> Add a krew.yaml meta-manifest template

- README.md
- hack/krew.yaml
- hack/make-release-artifacts.sh
> Remove archive indirection

- cmd/krew/cmd/info.go
- cmd/krew/cmd/install.go
> cmd: prevent formatting in caveats

- docs/RELEASING_KREW.md
> docs: document releasing version on index

- hack/make-release-notes.sh
Probably useful for next time.
> hack: add krew.yaml to release notes

- docs/DEVELOPER_GUIDE.md
with feedback from some internal friction log.
> docs: update developer guide

- pkg/download/downloader.go
- pkg/download/downloader_test.go
- pkg/download/fetch.go
- pkg/download/verifier.go
- pkg/download/verifier_test.go
- pkg/installation/install.go
The first part of increasing the test coverage for the download package.
/ref #47
> Add download tests

- OWNERS_ALIASES
> Add myself as krew maintainer

- README.md
Since we passed 1k recently, worth celebrating. :cocktail:
> README: add github stars from shields.io

- hack/run-lint.sh
> hack: make run-lint.sh work with go modules

- README.md
ref: #303
/hold
until https://github.com/kubernetes-sigs/krew-index/pull/202 merged.
> README: link to the list of available plugins

- pkg/index/indexscanner/scanner.go
> pkg/index: close manifest file after reading

- cmd/krew/cmd/list.go
- hack/run-lint.sh
..and fix one new issue
Release notes for linter: https://github.com/golangci/golangci-lint/releases/tag/v1.19.0
> Upgrade to golangci-lint v0.19.0

- pkg/download/downloader_test.go
- pkg/download/verifier.go
- pkg/download/verifier_test.go
This verifier implementation is only used in tests, so it should be defined there.
> Remove trueVerifier from main logic

- pkg/download/downloader.go
- pkg/download/fetch.go
- pkg/installation/install.go
> Improve error messages when installing from manifest+archive

- cmd/generate-plugin-overview/generate-plugin-overview.go
Proper solution to https://github.com/kubernetes-sigs/krew-index/pull/296
> Added condition for generating KUDO github stars

- hack/.gitignore
- hack/make-release-notes.sh
As mentioned in https://github.com/kubernetes-sigs/krew/issues/324#issuecomment-526905406
> Include list of merged pull requests in release notes

- hack/make-release-notes.sh
Sigh.. go modules is hard.
See comment https://github.com/kubernetes-sigs/krew/pull/326#issuecomment-552164347
/assign @ahmetb
> Pin version of release-notes helper

- hack/run-lint.sh
Incremental analysis is added.
> Update golangci-lint to v1.21.0

- pkg/gitutil/git.go
> Clean untracked files while updating index

- docs/DEVELOPER_GUIDE.md
- explicitly show that you need to install a LICENSE file
- mention size limitations in shortDescription
> [docs] Improve annotated plugin manifest

- docs/RELEASING_KREW.md
> docs: Improvements to release doc

- cmd/krew/cmd/update.go
> Show smaller output for updated plugins list

- cmd/generate-plugin-overview/generate-plugin-overview.go
> Add special case for `virt` plugin

- docs/RELEASING_KREW.md
> Use tagged temp dirs to simplify cleanup

- netlify.toml
From: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#example-netlify-configuration
> site: Add netlify.toml

- docs/KREW_LOGO.md
> docs: Explain krew logo

- site/content/_index.md
- site/layouts/index.html
- site/layouts/partials/footer.html
- site/static/css/style.css
* rewrite the home page
* override .lead class and use it on the home page (/)
> site: landing page adjustments

- cmd/generate-plugin-overview/generate-plugin-overview.go
Add popeye known homepage to allow displaying Github stars image.
> add popeye known homepage

- site/content/docs/developer-guide/release/release-automation.md
> site: fix url for release-automation

- internal/installation/util_test.go
While parsing into a Plugin works here, what we really parse is Receipts,
so use that.
/cc @chriskim06
> ListInstalledPlugins use Receipts for parsing

- site/content/docs/developer-guide/distributing-with-krew.md
> site: Add "why distribute with Krew" section

- integration_test/list_test.go
To test this, I've manufactured receipts of all plugins in the index and
pretend they're coming from indexes "", "default", "bar".
Related issue: #560
> test: validate krew list output is sorted alphabetically

- integration_test/testutil_test.go
mtail just recently became a larger Go based plugin, so change.
> integration_test: change validPlugin2

- .github/workflows/ci.yml
> Switch to actions/setup-go@v2 to avoid PATH hack

- site/content/docs/developer-guide/custom-indexes.md
- site/content/docs/user-guide/using-custom-indexes.md
:tada::tada::tada:
Related issue: #566 
/cc @ahmetb 
> Publish custom index docs

- README.md
Today the plugins count is around 118 so pretty much fair
to increase the README to at least 100 :). Well done guys!
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> README: update the number of plugins count

- README.md
Fixes #651 
Hi, i just create pr to fixes issue #651
> docs(README.md): Remove Travis CI badge and use GitHub CI badge

- site/content/docs/user-guide/configuration.md
> site: Document KREW_ROOT

- cmd/krew/cmd/root.go
Requesting a pull to kubernetes-sigs:master from ahmetb:fix-typo
Write a message for this pull request. The first block
of text is the title and the rest is the description.
> fix typo in logs

- site/content/docs/user-guide/configuration.md
- site/content/docs/user-guide/install.md
- site/content/docs/user-guide/list.md
- site/content/docs/user-guide/quickstart.md
- site/content/docs/user-guide/search.md
- site/content/docs/user-guide/setup/install.md
- site/content/docs/user-guide/setup/uninstall.md
- site/content/docs/user-guide/setup/updates.md
- site/content/docs/user-guide/upgrade.md
- site/content/docs/user-guide/using-custom-indexes.md
This is just the user guide portion of changes, I figured it would be good to split them up to make it easier to keep track of these changes. Let me know if you want me to just include them all in this one and I can add the rest.
> Docs update - user guide

- site/layouts/partials/footer.html
Fixes #742 
Preview link : https://deploy-preview-746--kubernetes-sigs-krew.netlify.app/plugins/
Click the badge && you will be redirected to the corresponding github repo
> add prefix for rel attribute of badge

- site/content/docs/user-guide/setup/install.md
> Improved a installation script for fish

- docs/RELEASING_KREW.md
Fixes #792 
Related issue: #792
> Typos fixed in RELEASING_KREW.md

- CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #803
> Broken Link issue fixed

- internal/gitutil/git.go
Fixes #737
See https://github.com/golang/review/commit/9615674405d24ddf198471f1dd2d30fc558642b9
> Add workaround for msys2/cygwin git

- cmd/krew/cmd/root.go
> Fix: Non-constant format string in PrintWarning
